@server = http://localhost:3000

### 회원 가입
POST {{server}}/auth/register
Content-Type: application/json

{
    "username": "Lee",
    "password": "test1234",
    "email": "test@naver.com"
}

### 로그인
POST  {{server}}/auth/login
Content-Type: application/json

{
    "email": "test@naver.com",
    "password": "test1234"
}

### 프로필 확인
GET  {{server}}/auth/profile

### 프로필 확인2
GET {{server}}/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZlOGFiNDRiNGVmODBiMzdmOGVkYjMiLCJ1c2VybmFtZSI6IkxlZSIsImFkbWluIjpmYWxzZSwiaWF0IjoxNjk0NDkwNDMzLCJleHAiOjE2OTQ0OTA0NDN9.0Q2CdlFtZ-EMFvnqtROCOdbtzaSvmWNWvLZvEmXHG1o

### 리프레쉬 토큰 테스트
POST  {{server}}/auth/refresh
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZlOGFiNDRiNGVmODBiMzdmOGVkYjMiLCJ1c2VybmFtZSI6IkxlZSIsImFkbWluIjpmYWxzZSwiaWF0IjoxNjk0NDM4MTcyLCJleHAiOjE2OTUwNDI5NzJ9._97QafHZ6VdhKdAmPhaSLvXxeB1enL0_vjDW3VgixKs"
}

### 리프레쉬 토큰 쿠키 테스트
POST  {{server}}/auth/refresh
Content-Type: application/json
credentials: 'include'

### 로그아웃 테스트
POST  {{server}}/auth/logout
